version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql_project:/sql_project
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"